app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# As per: http://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc