# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    stl:
        class: AppBundle\Service\STL\STL
        arguments: [ "@service_container", 'stlFileReader', 'stlMillingEdit' ]
    stlFileReader:
        class: AppBundle\Service\STL\STLFileReader
        arguments: []
    stlMillingEdit:
        class: AppBundle\Service\STL\STLMillingEdit
        arguments: []
